export const tempData = [
  {
    "idMeal": "52771",
    "strMeal": "Spicy Arrabiata Penne",
    "strDrinkAlternate": null,
    "strCategory": "Vegetarian",
    "strArea": "Italian",
    "strInstructions": "Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.",
    "strMealThumb": "https:\/\/www.themealdb.com\/images\/media\/meals\/ustsqw1468250014.jpg",
    "strTags": "Pasta,Curry",
    "strYoutube": "https:\/\/www.youtube.com\/watch?v=1IszT_guI08",
    "strIngredient1": "penne rigate",
    "strIngredient2": "olive oil",
    "strIngredient3": "garlic",
    "strIngredient4": "chopped tomatoes",
    "strIngredient5": "red chile flakes",
    "strIngredient6": "italian seasoning",
    "strIngredient7": "basil",
    "strIngredient8": "Parmigiano-Reggiano",
    "strIngredient9": "",
    "strIngredient10": "",
    "strIngredient11": "",
    "strIngredient12": "",
    "strIngredient13": "",
    "strIngredient14": "", 
    "strIngredient15": "",
    "strIngredient16":null,
    "strIngredient17":null,
    "strIngredient18":null,
    "strIngredient19":null,
    "strIngredient20":null,
    "strMeasure1": "1 pound",
    "strMeasure2":"1\/4 cup",
    "strMeasure3":"3 cloves",
    "strMeasure4":"1 tin ",
    "strMeasure5":"1\/2 teaspoon",
    "strMeasure6":"1\/2 teaspoon",
    "strMeasure7":"6 leaves",
    "strMeasure8":"spinkling",
    "strMeasure9":"",
    "strMeasure10":"",
    "strMeasure11":"",
    "strMeasure12":"",
    "strMeasure13":"",
    "strMeasure14":"",
    "strMeasure15":"",
    "strMeasure16":null,
    "strMeasure17":null,
    "strMeasure18":null,
    "strMeasure19":null,
    "strMeasure20":null,
    "strSource":null,
    "strImageSource":null,
    "strCreativeCommonsConfirmed":null,
    "dateModified":null
  },

  {
    "idMeal":"52960",
    "strMeal":"Salmon Avocado Salad",
    "strDrinkAlternate":null,
    "strCategory":"Seafood",
    "strArea":"British",
    "strInstructions":"Season the salmon, then rub with oil. Mix the dressing ingredients together. Halve, stone, peel and slice the avocados. Halve and quarter the cucumber lengthways, then cut into slices. Divide salad, avocado and cucumber between four plates, then drizzle with half the dressing.\r\n\r\nHeat a non-stick pan. Add the salmon and fry for 3-4 mins on each side until crisp but still moist inside. Put a salmon fillet on top of each salad and drizzle over the remaining dressing. Serve warm.",
    "strMealThumb":"https:\/\/www.themealdb.com\/images\/media\/meals\/1549542994.jpg",
    "strTags":"Paleo,Keto,LowCarbs,Salad,Alcoholic,Halloween,",
    "strYoutube":"https:\/\/www.youtube.com\/watch?v=FJiu2S0Xap0",
    "strIngredient1":"Salmon",
    "strIngredient2":"Avocado",
    "strIngredient3":"Cucumber",
    "strIngredient4":"Spinach",
    "strIngredient5":"Mint",
    "strIngredient6":"Lime",
    "strIngredient7":"Honey",
    "strIngredient8":"Olive Oil",
    "strIngredient9":"",
    "strIngredient10":"",
    "strIngredient11":"",
    "strIngredient12":"",
    "strIngredient13":"",
    "strIngredient14":"",
    "strIngredient15":"",
    "strIngredient16":"",
    "strIngredient17":"",
    "strIngredient18":"",
    "strIngredient19":"",
    "strIngredient20":"",
    "strMeasure1":"400g",
    "strMeasure2":"3",
    "strMeasure3":"1",
    "strMeasure4":"400g",
    "strMeasure5":"4 tbs",
    "strMeasure6":"zest and juice of 1",
    "strMeasure7":"2 tsp",
    "strMeasure8":"3 tbs",
    "strMeasure9":"",
    "strMeasure10":"",
    "strMeasure11":"",
    "strMeasure12":"",
    "strMeasure13":"",
    "strMeasure14":"",
    "strMeasure15":"",
    "strMeasure16":"",
    "strMeasure17":"",
    "strMeasure18":"",
    "strMeasure19":"",
    "strMeasure20":"",
    "strSource":"https:\/\/www.bbcgoodfood.com\/recipes\/4521\/salmon-avocado-and-cucumber-salad",
    "strImageSource":null,
    "strCreativeCommonsConfirmed":null,
    "dateModified":null
  }
]